use CitiZone
EXEC addCategories N'DX', N'ĐÁ XAY'
EXEC addCategories N'ST', N'SINH TỐ'
EXEC addCategories N'TRA', N'TRÀ'
EXEC addCategories N'TR', N'TORRINGS'
EXEC addCategories N'CFVN', N'CÀ PHÊ'
EXEC addCategories N'TS', N'TRÀ SỮA'
EXEC addCategories N'SD', N'SODA'
EXEC addCategories N'MM', N'MOJITO MOCKTAIL'
EXEC addCategories N'SC', N'SỮA CHUA'


EXEC addFoods N'Cà phê Đá xay', '30000', N'DX'
EXEC addFoods N'Đá xay Ca-ra-men', '30000', N'DX'
EXEC addFoods N'Đá xay Hạt dẻ', '30000', N'DX'
EXEC addFoods N'Chocolate Đá xay', '30000', N'DX'
EXEC addFoods N'Chocolate Đá xay Bạc hà', '35000', N'DX'
EXEC addFoods N'Matcha Đá xay', '35000', N'DX'

EXEC addFoods N'Sinh tố Dâu', '35000', N'ST'
EXEC addFoods N'Sinh tố Việt Quất', '35000', N'ST'
EXEC addFoods N'Sinh tố Xoài Chanh Dây', '30000', N'ST'
EXEC addFoods N'Sinh tố Chanh Dây', '25000', N'ST'
EXEC addFoods N'Sinh tố Sapoche', '25000', N'ST'

EXEC addFoods N'Trà Đào', '25000', N'TRA'
EXEC addFoods N'Trà Táo', '25000', N'TRA'
EXEC addFoods N'Trà Đen', '35000', N'TRA'
EXEC addFoods N'Trà Olong', '30000', N'TRA'
EXEC addFoods N'Trà Lipton', '25000', N'TRA'
EXEC addFoods N'Matcha Latte', '35000', N'TRA'

EXEC addFoods N'Thạch', '5000', N'TR'
EXEC addFoods N'Trân châu', '5000', N'TR'
EXEC addFoods N'Trân châu trắng 3Q', '8000', N'TR'
EXEC addFoods N'Đào miếng', '10000', N'TR'
EXEC addFoods N'Kem thêm', '10000', N'TR'
EXEC addFoods N'Milkfoam', '10000', N'TR'

EXEC addFoods N'Cà phê Đen (Đá/Nóng)', '15000', N'CFVN'
EXEC addFoods N'Cà phê Sữa (Đá/Nóng)', '18000', N'CFVN'
EXEC addFoods N'Bạc Xỉu (Đá/Nóng)', '22000', N'CFVN'
EXEC addFoods N'Cà phê Lattle', '30000', N'CFVN'
EXEC addFoods N'Cà phê Cốt Dừa', '35000', N'CFVN'

EXEC addFoods N'Trà sữa thái xanh', '22000', N'TS'
EXEC addFoods N'Trà sữa thái đỏ', '22000', N'TS'
EXEC addFoods N'Trà đào sữa', '27000', N'TS'
EXEC addFoods N'Trà táo sữa', '27000', N'TS'
EXEC addFoods N'Trà sữa milkfoam', '27000', N'TS'

EXEC addFoods N'Green Leaf Soda', '25000', N'SD'
EXEC addFoods N'Grey Soda', '25000', N'SD'
EXEC addFoods N'Blue Ocean Soda', '25000', N'SD'
EXEC addFoods N'Soda Dâu', '25000', N'SD'
EXEC addFoods N'Soda Chanh Dây', '25000', N'SD'
EXEC addFoods N'Soda Kiwi', '25000', N'SD'
EXEC addFoods N'Soda Bạc Hà', '25000', N'SD'

EXEC addFoods N'Mojito Dâu', '28000', N'MM'
EXEC addFoods N'Mojito Chanh Dây', '28000', N'MM'
EXEC addFoods N'Mojito Kiwi', '28000', N'MM'
EXEC addFoods N'Mojito Xoài', '28000', N'MM'
EXEC addFoods N'Mojito Việt Quất', '28000', N'MM'
EXEC addFoods N'Mojito Phúc Bồn Tử', '28000', N'MM'

EXEC addFoods N'Sữa Chua Dâu', '25000', N'SC'
EXEC addFoods N'Sữa Chua Chanh Dây', '25000', N'SC'
EXEC addFoods N'Sữa Chua Kiwi', '25000', N'SC'
EXEC addFoods N'Sữa Chua Việt Quất', '25000', N'SC'
EXEC addFoods N'Sữa Chua Phúc Bồn Tử', '25000', N'SC'
EXEC addFoods N'Sữa Chua Xoài', '25000', N'SC'
